insert into arrests (State,
    Male,
    Female,
    Total,
    Rape,
    Arson,
    Fraud,
    Larceny,
    Robbery,
    Runaway,
    Weapons,
    Burglary,
    Gambling,
    Vagrancy,
    Suspicion,
    Vandalism,
    Drunkenness,
    Embezzlement,
    Sex_Offenses,
    Rape_Legacy,
    Simple_Assault,
    Drug_Possession,
    Stolen_Property,
    Human_Trafficking,
    Aggravated_Assault,
    All_Other_Offenses,
    Disorderly_Conduct,
    Motor_Vehicle_Theft,
    Drug_Abuse_Violations,
    Liquor_Law_Violations,
    Counterfeiting_or_Forgery,
    Drug_Sale_or_Manufacturing,
    Drive_Under_the_Influence,
    Manslaughter_by_Negligence,
    Murder_and_Nonnegligent_Homicide,
    Curfew_and_Loitering_Law_Violations,
    Prostitution_and_Commercialized_Vice,
    Offenses_Against_the_Family_and_Children,
    Asian,
    White,
    Unknown,
    Multiple,
    NotSpecified,
    Black,
    NativeAmerican,
    NativeHawaiianOrPacificIslander,
	Male_Age_15,
	Male_Age_16,
	Male_Age_17,
	Male_Age_18,
	Male_Age_19,
	Male_Age_20,
	Male_Age_21,
	Male_Age_22,
	Male_Age_23,
	Male_Age_24,
	Male_Age_10_12,
	Male_Age_11_12,
	Male_Age_13_14,
	Male_Age_25_29,
	Male_Age_30_34,
	Male_Age_35_39,
	Male_Age_40_44,
	Male_Age_45_49,
	Male_Age_50_54,
	Male_Age_55_59,
	Male_Age_60_64,
	Male_Age_Under_10,
	Male_Age_Under_11,
	Male_Age_65_and_over,
	Male_Age_Adult_Other,
	Male_Age_Juvenile_Other,
	Female_Age_15,
	Female_Age_16,
	Female_Age_17,
	Female_Age_18,
	Female_Age_19,
	Female_Age_20,
	Female_Age_21,
	Female_Age_22,
	Female_Age_23,
	Female_Age_24,
	Female_Age_10_12,
	Female_Age_11_12,
	Female_Age_13_14,
	Female_Age_25_29,
	Female_Age_30_34,
	Female_Age_35_39,
	Female_Age_40_44,
	Female_Age_45_49,
	Female_Age_50_54,
	Female_Age_55_59,
	Female_Age_60_64,
	Female_Age_Under_10,
	Female_Age_Under_11,
	Female_Age_65_and_over,
	Female_Age_Adult_Other,
	Female_Age_Juvenile_Other
)
select '{state}',
    json_extract(json, '$.Arrestee Sex.Male'),
    json_extract(json, '$.Arrestee Sex.Female'),
    json_extract(json, '$.Arrestee Sex.Male') + json_extract(json, '$.Arrestee Sex.Female'),
    json_extract(json, '$.Offense Name.Rape'),
    json_extract(json, '$.Offense Name.Arson'),
    json_extract(json, '$.Offense Name.Fraud'),
    json_extract(json, '$.Offense Name.Larceny'),
    json_extract(json, '$.Offense Name.Robbery'),
    json_extract(json, '$.Offense Name.Runaway'),
    json_extract(json, '$.Offense Name.Weapons'),
    json_extract(json, '$.Offense Name.Burglary'),
    json_extract(json, '$.Offense Name.Gambling'),
    json_extract(json, '$.Offense Name.Vagrancy'),
    json_extract(json, '$.Offense Name.Suspicion'),
    json_extract(json, '$.Offense Name.Vandalism'),
    json_extract(json, '$.Offense Name.Drunkenness'),
    json_extract(json, '$.Offense Name.Embezzlement'),
    json_extract(json, '$.Offense Name.Sex Offenses'),
    json_extract(json, '$.Offense Name.Rape (Legacy)'),
    json_extract(json, '$.Offense Name.Simple Assault'),
    json_extract(json, '$.Offense Name.Drug Possession'),
    json_extract(json, '$.Offense Name.Stolen Property'),
    json_extract(json, '$.Offense Name.Human Trafficking'),
    json_extract(json, '$.Offense Name.Aggravated Assault'),
    json_extract(json, '$.Offense Name.All Other Offenses'),
    json_extract(json, '$.Offense Name.Disorderly Conduct'),
    json_extract(json, '$.Offense Name.Motor Vehicle Theft'),
    json_extract(json, '$.Offense Name.Drug Abuse Violations'),
    json_extract(json, '$.Offense Name.Liquor Law Violations'),
    json_extract(json, '$.Offense Name.Counterfeiting/Forgery'),
    json_extract(json, '$.Offense Name.Drug Sale/Manufacturing'),
    json_extract(json, '$.Offense Name.Drive Under the Influence'),
    json_extract(json, '$.Offense Name.Manslaughter by Negligence'),
    json_extract(json, '$.Offense Name.Murder and Nonnegligent Homicide'),
    json_extract(json, '$.Offense Name.Curfew and Loitering Law Violations'),
    json_extract(json, '$.Offense Name.Prostitution and Commercialized Vice'),
    json_extract(json, '$.Offense Name.Offenses Against the Family and Children'),
    json_extract(json, '$.Arrestee Race.Asian'),
    json_extract(json, '$.Arrestee Race.White'),
    json_extract(json, '$.Arrestee Race.Unknown'),
    json_extract(json, '$.Arrestee Race.Multiple'),
    json_extract(json, '$.Arrestee Race.Not Specified'),
    json_extract(json, '$.Arrestee Race.Black or African American'),
    json_extract(json, '$.Arrestee Race.American Indian or Alaska Native'),
    json_extract(json, '$.Arrestee Race.Native Hawaiian or Other Pacific Islander'),
	json_extract(json, '$.Male Arrests By Age.15'),
	json_extract(json, '$.Male Arrests By Age.16'),
	json_extract(json, '$.Male Arrests By Age.17'),
	json_extract(json, '$.Male Arrests By Age.18'),
	json_extract(json, '$.Male Arrests By Age.19'),
	json_extract(json, '$.Male Arrests By Age.20'),
	json_extract(json, '$.Male Arrests By Age.21'),
	json_extract(json, '$.Male Arrests By Age.22'),
	json_extract(json, '$.Male Arrests By Age.23'),
	json_extract(json, '$.Male Arrests By Age.24'),
	json_extract(json, '$.Male Arrests By Age.10-12'),
	json_extract(json, '$.Male Arrests By Age.11-12'),
	json_extract(json, '$.Male Arrests By Age.13-14'),
	json_extract(json, '$.Male Arrests By Age.25-29'),
	json_extract(json, '$.Male Arrests By Age.30-34'),
	json_extract(json, '$.Male Arrests By Age.35-39'),
	json_extract(json, '$.Male Arrests By Age.40-44'),
	json_extract(json, '$.Male Arrests By Age.45-49'),
	json_extract(json, '$.Male Arrests By Age.50-54'),
	json_extract(json, '$.Male Arrests By Age.55-59'),
	json_extract(json, '$.Male Arrests By Age.60-64'),
	json_extract(json, '$.Male Arrests By Age.Under 10'),
	json_extract(json, '$.Male Arrests By Age.Under 11'),
	json_extract(json, '$.Male Arrests By Age.65 and over'),
	json_extract(json, '$.Male Arrests By Age.Adult Other'),
	json_extract(json, '$.Male Arrests By Age.Juvenile Other'),
	json_extract(json, '$.Female Arrests By Age.15'),
	json_extract(json, '$.Female Arrests By Age.16'),
	json_extract(json, '$.Female Arrests By Age.17'),
	json_extract(json, '$.Female Arrests By Age.18'),
	json_extract(json, '$.Female Arrests By Age.19'),
	json_extract(json, '$.Female Arrests By Age.20'),
	json_extract(json, '$.Female Arrests By Age.21'),
	json_extract(json, '$.Female Arrests By Age.22'),
	json_extract(json, '$.Female Arrests By Age.23'),
	json_extract(json, '$.Female Arrests By Age.24'),
	json_extract(json, '$.Female Arrests By Age.10-12'),
	json_extract(json, '$.Female Arrests By Age.11-12'),
	json_extract(json, '$.Female Arrests By Age.13-14'),
	json_extract(json, '$.Female Arrests By Age.25-29'),
	json_extract(json, '$.Female Arrests By Age.30-34'),
	json_extract(json, '$.Female Arrests By Age.35-39'),
	json_extract(json, '$.Female Arrests By Age.40-44'),
	json_extract(json, '$.Female Arrests By Age.45-49'),
	json_extract(json, '$.Female Arrests By Age.50-54'),
	json_extract(json, '$.Female Arrests By Age.55-59'),
	json_extract(json, '$.Female Arrests By Age.60-64'),
	json_extract(json, '$.Female Arrests By Age.Under 10'),
	json_extract(json, '$.Female Arrests By Age.Under 11'),
	json_extract(json, '$.Female Arrests By Age.65 and over'),
	json_extract(json, '$.Female Arrests By Age.Adult Other'),
	json_extract(json, '$.Female Arrests By Age.Juvenile Other')
from stage_state;