insert into derived_columns_stage(
    State,
    RecidivismRate,
    PercentMale,
    PercentFemale,
    PercentAsian,
    PercentWhite,
    PercentBlack,
    PercentNativeAmerican,
    PercentOfPopInPrison,
    TotalViolentCrimes,
    TotalNonviolentCrimes,
    OtherCrimes,
    AverageQOLScore,
    PopulationDensity
)
select 
    State,
    RecidivismRate,
    Male*1.0/Total,
    Female*1.0/Total,
    Asian*1.0/Total,
    White*1.0/Total,
    Black*1.0/Total,
    NativeAmerican*1.0/Total,
    prisonpopulation*1.0/population,
    (Rape+
        Robbery+
        Weapons+
        Burglary+
        Sex_Offenses+
        Rape_Legacy+
        Simple_Assault+
        Aggravated_Assault+
        Murder_and_Nonnegligent_Homicide
        ),
    (Fraud+
        Larceny+
        Runaway+
        Gambling+
        Vagrancy+
        Suspicion+
        Vandalism+
        Drunkenness+
        Embezzlement+
        Drug_Possession+
        Stolen_Property+
        Human_Trafficking+
        Disorderly_Conduct+
        Motor_Vehicle_Theft+
        Drug_Abuse_Violations+
        Liquor_Law_Violations+
        Counterfeiting_or_Forgery+
        Drug_Sale_or_Manufacturing+
        Drive_Under_the_Influence+
        Manslaughter_by_Negligence+
        Curfew_and_Loitering_Law_Violations+
        Prostitution_and_Commercialized_Vice+
        Offenses_Against_the_Family_and_Children),
    (Arson+
        All_Other_Offenses
        ),
    (qualityoflifetotalscore+
        qualityoflifeaffordability+
        qualityoflifeeconomy+
        qualityoflifeeducationandhealth+
        qualityoflifesafety)/5.0,
    population/SquareMiles
from stage